/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as RouteTreeImport } from './routes/routeTree';
import { Route as AboutRouteImport } from './routes/about.route';
import { Route as IndexRouteImport } from './routes/index.route';

// Create/Update Routes

const RouteTreeRoute = RouteTreeImport.update({
  id: '/routeTree',
  path: '/routeTree',
  getParentRoute: () => rootRoute,
} as any);

const AboutRouteRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any);

const IndexRouteRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/routeTree': {
      id: '/routeTree';
      path: '/routeTree';
      fullPath: '/routeTree';
      preLoaderRoute: typeof RouteTreeImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute;
  '/about': typeof AboutRouteRoute;
  '/routeTree': typeof RouteTreeRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute;
  '/about': typeof AboutRouteRoute;
  '/routeTree': typeof RouteTreeRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRouteRoute;
  '/about': typeof AboutRouteRoute;
  '/routeTree': typeof RouteTreeRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/about' | '/routeTree';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/about' | '/routeTree';
  id: '__root__' | '/' | '/about' | '/routeTree';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute;
  AboutRouteRoute: typeof AboutRouteRoute;
  RouteTreeRoute: typeof RouteTreeRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AboutRouteRoute: AboutRouteRoute,
  RouteTreeRoute: RouteTreeRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/routeTree"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/about": {
      "filePath": "about.route.tsx"
    },
    "/routeTree": {
      "filePath": "routeTree.ts"
    }
  }
}
ROUTE_MANIFEST_END */
